# "host":"172.31.98.138",
#             "database":"airflow_traffic_db",
#             "port":"5432",
#             "user":"postgres",
#             "password":"password"
my_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: 192.168.1.8         # e.g., localhost or IP address
      # host: 172.31.98.138         # e.g., localhost or IP address
      port: 5432                        # Default PostgreSQL port
      user: postgres               # Your PostgreSQL username
      password: password           # Your PostgreSQL password
      dbname: airflow_traffic_db             # Your database name
      schema: public               # Schema where dbt will create tables/views
