# "host":"172.31.98.138",
#             "database":"airflow_traffic_db",
#             "port":"5432",
#             "user":"postgres",
#             "password":"password"
my_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('HOST') }}"         # e.g., localhost or IP address
      port: "{{ env_var('PORT') | as_number }}"                        # Default PostgreSQL port
      user: "{{ env_var('USER') }}"               # Your PostgreSQL username
      password: "{{ env_var('PASSWORD') }}"           # Your PostgreSQL password
      dbname: "{{ env_var('DATABASE') }}"            # Your database name
      schema: public               # Schema where dbt will create tables/views
